language: node_js
cache:
  directories:
  - node_modules
after_failure:
  - ./scripts/upload-artifacts.sh /home/travis/build/dadi/publish-functional-tests/test/output
notifications:
  webhooks:
    urls:
      - http://github-webhooks.eb.dev.dadi.technology/travis-webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  email: false
  slack: false
node_js:
- '8'
